export const themeConfig = {
  name: 'Creator\'s Studio',
  description: 'Premium theme for creative prompt generation',
  light: {
    background: '#FAFBFC',
    foreground: '#1A202C',
    card: '#FFFFFF',
    cardForeground: '#1A202C',
    popover: '#F1F5F9',
    popoverForeground: '#1A202C',
    primary: '#6D28D9',
    primaryForeground: '#FFFFFF',
    secondary: '#E2E8F0',
    secondaryForeground: '#1A202C',
    muted: '#E2E8F0',
    mutedForeground: '#64748B',
    accent: '#E2E8F0',
    accentForeground: '#1A202C',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#E2E8F0',
    input: '#E2E8F0',
    ring: '#6D28D9',
  },
  dark: {
    background: '#0F172A',
    foreground: '#F1F5F9',
    card: '#1E293B',
    cardForeground: '#F1F5F9',
    popover: '#334155',
    popoverForeground: '#F1F5F9',
    primary: '#8B5CF6',
    primaryForeground: '#FFFFFF',
    secondary: '#334155',
    secondaryForeground: '#F1F5F9',
    muted: '#334155',
    mutedForeground: '#94A3B8',
    accent: '#334155',
    accentForeground: '#F1F5F9',
    destructive: '#F87171',
    destructiveForeground: '#FFFFFF',
    border: '#334155',
    input: '#334155',
    ring: '#8B5CF6',
  },
  fonts: {
    display: 'Inter',
    body: 'Inter',
    mono: 'JetBrains Mono',
  },
}
