export const themeConfig = {
  name: 'PromptForge IDE',
  description: 'IDE-inspired semantic theme for prompt engineering workflows',
  light: {
    background: '#FAFAFA',
    foreground: '#111317',
    card: '#FFFFFF',
    cardForeground: '#111317',
    popover: '#FFFFFF',
    popoverForeground: '#111317',
    primary: '#2F6FE0',
    primaryForeground: '#FFFFFF',
    secondary: '#F1F2F4',
    secondaryForeground: '#4B5563',
    muted: '#F1F2F4',
    mutedForeground: '#9CA3AF',
    accent: '#F1F2F4',
    accentForeground: '#111317',
    destructive: '#DC2626',
    destructiveForeground: '#FFFFFF',
    border: '#E5E7EB',
    input: '#E5E7EB',
    ring: '#2F6FE0',
  },
  dark: {
    background: '#0B0D10',
    foreground: '#F3F4F6',
    card: '#15181C',
    cardForeground: '#F3F4F6',
    popover: '#15181C',
    popoverForeground: '#F3F4F6',
    primary: '#5B8DF8',
    primaryForeground: '#FFFFFF',
    secondary: '#1E2227',
    secondaryForeground: '#9CA3AF',
    muted: '#1E2227',
    mutedForeground: '#6B7280',
    accent: '#1E2227',
    accentForeground: '#F3F4F6',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#2A2E34',
    input: '#2A2E34',
    ring: '#5B8DF8',
  },
  fonts: {
    display: 'Geist',
    body: 'Geist',
    mono: 'JetBrains Mono',
  },
}
